import type { DistrictId, LandmarkKind } from "lib/boring/map/types";

export const BHOPAL_MAP_CONFIG = {
  schemaVersion: 1 as const,
  bbox: [23.2, 77.35, 23.3, 77.47] as [number, number, number, number],
  origin: {
    latitude: 23.25,
    longitude: 77.41,
    label: "Central Bhopal compression origin",
  },
  worldScale: 0.01,
  quantization: 0.01,
  simplificationMeters: {
    motorway: 7,
    trunk: 6,
    primary: 5,
    secondary: 4,
    tertiary: 3,
    residential: 2.5,
    service: 2,
    railway: 4,
    polygon: 5,
  },
  roadWidths: {
    motorway: 3.4,
    trunk: 3.1,
    primary: 2.8,
    secondary: 2.45,
    tertiary: 2.05,
    residential: 1.55,
    service: 1.15,
  },
  includedHighways: [
    "motorway",
    "trunk",
    "primary",
    "secondary",
    "tertiary",
    "residential",
    "service",
  ],
} as const;

export type LandmarkConfig = {
  id: string;
  name: string;
  patterns: string[];
  kind: LandmarkKind;
  districtId: DistrictId;
  sensitive: boolean;
  fallback: [number, number]; // latitude, longitude; checked against OSM reference data
};

export const LANDMARK_CONFIG: LandmarkConfig[] = [
  {
    id: "upper-lake",
    name: "Upper Lake · Bhojtal",
    patterns: ["upper lake", "bhojtal", "bada talab", "bada talaab"],
    kind: "lake",
    districtId: "lakefront",
    sensitive: false,
    fallback: [23.2624, 77.3655],
  },
  {
    id: "lower-lake",
    name: "Lower Lake",
    patterns: ["lower lake", "chhota talab", "chhota talaab"],
    kind: "lake",
    districtId: "lakefront",
    sensitive: false,
    fallback: [23.2467, 77.4056],
  },
  {
    id: "kamla-park",
    name: "Kamla Park",
    patterns: ["kamla park"],
    kind: "park",
    districtId: "lakefront",
    sensitive: false,
    fallback: [23.2545, 77.3958],
  },
  {
    id: "taj-ul-masajid",
    name: "Taj-ul-Masajid",
    patterns: ["taj-ul-masajid", "taj ul masajid", "tajul masajid"],
    kind: "mosque",
    districtId: "old-city",
    sensitive: true,
    fallback: [23.2785, 77.3927],
  },
  {
    id: "gohar-mahal",
    name: "Gohar Mahal",
    patterns: ["gohar mahal", "gauhar mahal"],
    kind: "palace",
    districtId: "old-city",
    sensitive: true,
    fallback: [23.2562, 77.3979],
  },
  {
    id: "chowk-bazaar",
    name: "Chowk Bazaar",
    patterns: ["chowk bazaar", "chowk market"],
    kind: "market",
    districtId: "old-city",
    sensitive: false,
    fallback: [23.2671, 77.4026],
  },
  {
    id: "moti-masjid",
    name: "Moti Masjid",
    patterns: ["moti masjid"],
    kind: "mosque",
    districtId: "old-city",
    sensitive: true,
    fallback: [23.2623, 77.402],
  },
  {
    id: "bharat-bhavan",
    name: "Bharat Bhavan",
    patterns: ["bharat bhavan"],
    kind: "cultural",
    districtId: "shyamla-hills",
    sensitive: true,
    fallback: [23.2433, 77.3921],
  },
  {
    id: "tribal-museum",
    name: "Madhya Pradesh Tribal Museum",
    patterns: ["tribal museum", "jansangrahalaya"],
    kind: "museum",
    districtId: "shyamla-hills",
    sensitive: true,
    fallback: [23.2325, 77.385],
  },
  {
    id: "manav-sangrahalaya",
    name: "Manav Sangrahalaya",
    patterns: ["manav sangrahalaya", "museum of man", "rashtriya manav"],
    kind: "museum",
    districtId: "shyamla-hills",
    sensitive: true,
    fallback: [23.2402, 77.3724],
  },
  {
    id: "van-vihar",
    name: "Van Vihar edge",
    patterns: ["van vihar"],
    kind: "park",
    districtId: "shyamla-hills",
    sensitive: true,
    fallback: [23.2317, 77.3648],
  },
  {
    id: "new-market",
    name: "New Market · TT Nagar",
    patterns: ["new market", "tt nagar"],
    kind: "market",
    districtId: "new-bhopal",
    sensitive: false,
    fallback: [23.2336, 77.4011],
  },
  {
    id: "birla-mandir",
    name: "Birla Mandir",
    patterns: ["birla mandir", "lakshmi narayan temple", "laxmi narayan temple"],
    kind: "temple",
    districtId: "new-bhopal",
    sensitive: true,
    fallback: [23.2297, 77.4151],
  },
  {
    id: "shaurya-smarak",
    name: "Shaurya Smarak",
    patterns: ["shaurya smarak"],
    kind: "memorial",
    districtId: "new-bhopal",
    sensitive: true,
    fallback: [23.2338, 77.4307],
  },
  {
    id: "rani-kamlapati-station",
    name: "Rani Kamlapati Station",
    patterns: ["rani kamlapati", "habibganj railway station", "habibganj station"],
    kind: "station",
    districtId: "new-bhopal",
    sensitive: false,
    fallback: [23.2211, 77.4394],
  },
  {
    id: "db-mall",
    name: "DB City Mall",
    patterns: ["db city mall", "d b city mall"],
    kind: "mall",
    districtId: "new-bhopal",
    sensitive: false,
    fallback: [23.2321, 77.4302],
  },
];

export const DISTRICT_CONFIG = [
  {
    id: "lakefront" as const,
    name: "Lakefront · VIP Road",
    shortName: "LAKEFRONT",
    accent: "#5ca7a2",
    bbox: [23.238, 77.35, 23.286, 77.405] as [number, number, number, number],
  },
  {
    id: "old-city" as const,
    name: "Old City",
    shortName: "OLD CITY",
    accent: "#df604f",
    bbox: [23.252, 77.39, 23.3, 77.43] as [number, number, number, number],
  },
  {
    id: "shyamla-hills" as const,
    name: "Shyamla Hills",
    shortName: "SHYAMLA",
    accent: "#71865b",
    bbox: [23.2, 77.35, 23.252, 77.407] as [number, number, number, number],
  },
  {
    id: "new-bhopal" as const,
    name: "New Bhopal",
    shortName: "NEW BHOPAL",
    accent: "#e9b949",
    bbox: [23.2, 77.4, 23.263, 77.47] as [number, number, number, number],
  },
];
